build_cv_from_json:
	python build_data_rdf.py && \
		python build_cv.py && \
		pdflatex -output-directory ../curriculum_vitae ../curriculum_vitae/Rukmal\ Weerawarana\ -\ Curriculum\ Vitae.tex

build_resume_from_json:
	python build_data_rdf.py && \
		python build_resume.py && \
		pdflatex -output-director ../resume ../resume/Rukmal\ Weerawarana\ -\ Resume.tex
