build_cv_from_rdf:
		python build_cv.py && \
		pdflatex -output-directory ../curriculum_vitae ../curriculum_vitae/Rukmal\ Weerawarana\ -\ Curriculum\ Vitae.tex

build_resume_from_rdf:
		python build_resume.py && \
		pdflatex -output-directory ../resume ../resume/Rukmal\ Weerawarana\ -\ Resume.tex

build_data_rdf:
	python build_data_rdf.py
