name: Commit RDF, PDF, and TeX artifacts

on:
  push:
    branches:
      - gh-pages
      - master
      - main

jobs:
  build_commit_artifacts:
    uses: rukmal/resume/.github/workflows/build-artifacts.yml@gh-pages
  commit_sample_artifacts:
    needs: build_commit_artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download all sample artifacts
        uses: actions/download-artifact@v2
        with:
          name: generated-artifacts
          path: tmp/
      - name: Move artifacts to correct location
        run: |
          mv tmp/resume/* resume/
          mv tmp/curriculum_vitae/* curriculum_vitae/
          mv tmp/personal_data.rdf personal_data.rdf
      - name: Display added files
        run: git add . && git status
      - name: Commit sample artifacts to Pull Request
        uses: EndBug/add-and-commit@v7 # See: https://github.com/marketplace/actions/add-commit
        with:
          add: "."
          default_author: github_actions
          message: "[GitHub Actions] Commit generated artifacts"
